#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 20 18:56:43 UYT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Hysteria-Shaders-Universal-v1.2.1.zip
enableShaders=false
